language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "pypy3.5"
addons:
    apt:
        packages:
            - pep8
script:
  - python setup.py test
  - pep8 openfoodfacts/*.py
  
notifications:
  slack: openfoodfacts:kVMm929AwnFUHXzB8UXU01gG
